### ISSUE TITLE
pure css

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/js-slippymap-crosshairs#1]
could do a pure css version such as:

``` css
body:before, body:after {
  content: '';
  position: fixed;
  left: 50%;
  top: 50%;
  -ms-transform: translate(-50%, -50%);
  -webkit-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  pointer-events: none;
  background: black;
  z-index: 1000;
}

body:before {
  width: 50px;
  height: 1px;
}

body:after {
  width: 1px;
  height: 50px;
}
```

**Comment by thisisaaronland** [comment]
Ah, interesting. This looks like it assumes a full-screen map. Will this work the when applied to `#map` as `body` ?

**Comment by missinglink** [comment]
I'm not that sharp at the front-end, a friend of mine wrote it for me, I assume it would work fine applied to any div with fixed width/height. I'm not so sure about fluid layouts, I'm sure @louh would know.

**Comment by louh** [comment]
@thisisaaronland Not as written; `position: fixed` won't move with the map if it scrolls away.

This works better:

``` css
.leaflet-container:before, .leaflet-container:after {
  content: '';
  position: absolute;
  left: 50%;
  top: 50%;
  -ms-transform: translate(-50%, -50%);
  -webkit-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  pointer-events: none;
  background: black;
  z-index: 1000;
}

.leaflet-container:before {
  width: 50px;
  height: 1px;
}

.leaflet-container:after {
  width: 1px;
  height: 50px;
}
```

(This is also in case you want it to apply to all Leaflet instances and not just `#whateverid`)

The problem with attaching yourself to the Leaflet container's pseudo-elements as a generic library, is that if every library does it then chaos ensues. Sure, I want a crosshairs plugin on my Leaflet, but what if leaflet-random-balloon-animals.js also wants to attach their own styles to the pseudo element? It is still better to have _some JavaScript_, register yourself as Leaflet plugin and create an appropriate DOM element as a control layer you can attach your styles to.
